# Generated by Django 5.2.9 on 2025-12-22 04:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('eligibility', models.TextField()),
                ('documents', models.TextField()),
                ('apply_link', models.URLField()),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('age_min', models.IntegerField(blank=True, null=True)),
                ('age_max', models.IntegerField(blank=True, null=True)),
                ('applicable_states', models.CharField(help_text='Comma-separated list of states', max_length=500)),
                ('applicable_occupations', models.CharField(blank=True, help_text='Comma-separated list of occupations', max_length=500, null=True)),
                ('benefits', models.TextField()),
                ('application_process', models.TextField()),
                ('contact_info', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Scheme',
                'verbose_name_plural': 'Schemes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SchemeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('viewed', 'Viewed'), ('applied', 'Applied'), ('saved', 'Saved'), ('shared', 'Shared')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_history', to='schemes.scheme')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheme_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Scheme History',
                'verbose_name_plural': 'Scheme Histories',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SchemeReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('sent', 'Sent'), ('completed', 'Completed')], default='active', max_length=20)),
                ('reminder_type', models.CharField(choices=[('deadline', 'Deadline'), ('application', 'Application Started'), ('completion', 'Document Completion')], default='deadline', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='schemes.scheme')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheme_reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Scheme Reminder',
                'verbose_name_plural': 'Scheme Reminders',
                'ordering': ['reminder_date'],
            },
        ),
        migrations.CreateModel(
            name='DocumentChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documents', models.JSONField(default=dict)),
                ('age', models.IntegerField()),
                ('occupation', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('completion_percentage', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_checklists', to=settings.AUTH_USER_MODEL)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_checklists', to='schemes.scheme')),
            ],
            options={
                'verbose_name': 'Document Checklist',
                'verbose_name_plural': 'Document Checklists',
                'unique_together': {('user', 'scheme')},
            },
        ),
        migrations.CreateModel(
            name='UserSavedScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_users', to='schemes.scheme')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_schemes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Saved Scheme',
                'verbose_name_plural': 'User Saved Schemes',
                'unique_together': {('user', 'scheme')},
            },
        ),
    ]
